
import __ASTRO_IMAGE_IMPORT_ZFJg8a from "./7-essential-websites-for-software-engineers-daily.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F7-essential-websites-for-software-engineers-daily%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2x0i8R from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fa-complete-guide-to-the-product-design-process%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1ISwgD from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fci-cd-for-llm-apps-run-tests-with-evidently-github-actions%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZPu9DW from "./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-native-devsecops-resilient-software%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2pIsE1 from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffree-llm-and-gen-ai-courses-to-take-in-2025%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_iX67l from "./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-not-write-garbage-code-by-linus-torvalds%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZYugHK from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-choose-a-trusted-web-development-company-2025-guide%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZR0q6k from "./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-tech-is-built-for-you-to-fail-why-smart-design-embraces-human-error%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_165AWF from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-optimize-your-seo-strategy-for-google-ai-overviews-in-2025%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1YVcnY from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fis-wordpress-still-the-best-cms-in-2025%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1dgxFm from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Four-startup-story-how-aexaware-infotech-was-born-in-anand-gujarat%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2sbaxF from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fowasp-top-10-llm-how-to-test-your-gen-ai-app-in-2025%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2vNsgs from "./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-19-2-features-that-transform-app-performance%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z8wqcg from "./cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftaming-data-variety-ai-ml-integration-cloud-devops%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1476Vv from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftop-ai-tools-for-web-development-in-2025%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1tV55M from "./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-80-of-modern-systems-fail-not-from-bugs-but-from-over-engineering%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZqOSrV from "./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-stripes-api-never-breaks-date-based-versioning-explained%2Findex.mdx";
export default new Map([["./7-essential-websites-for-software-engineers-daily.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F7-essential-websites-for-software-engineers-daily%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZFJg8a], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fa-complete-guide-to-the-product-design-process%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2x0i8R], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fci-cd-for-llm-apps-run-tests-with-evidently-github-actions%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1ISwgD], ["./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-native-devsecops-resilient-software%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZPu9DW], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffree-llm-and-gen-ai-courses-to-take-in-2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_2pIsE1], ["./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-not-write-garbage-code-by-linus-torvalds%2Findex.mdx", __ASTRO_IMAGE_IMPORT_iX67l], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-choose-a-trusted-web-development-company-2025-guide%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZYugHK], ["./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-tech-is-built-for-you-to-fail-why-smart-design-embraces-human-error%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZR0q6k], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-optimize-your-seo-strategy-for-google-ai-overviews-in-2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_165AWF], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fis-wordpress-still-the-best-cms-in-2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1YVcnY], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Four-startup-story-how-aexaware-infotech-was-born-in-anand-gujarat%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1dgxFm], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fowasp-top-10-llm-how-to-test-your-gen-ai-app-in-2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_2sbaxF], ["./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Freact-19-2-features-that-transform-app-performance%2Findex.mdx", __ASTRO_IMAGE_IMPORT_2vNsgs], ["./cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftaming-data-variety-ai-ml-integration-cloud-devops%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z8wqcg], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftop-ai-tools-for-web-development-in-2025%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1476Vv], ["./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-80-of-modern-systems-fail-not-from-bugs-but-from-over-engineering%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1tV55M], ["./cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-stripes-api-never-breaks-date-based-versioning-explained%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZqOSrV]]);
		