
export default new Map([
["src/content/blog/7-essential-websites-for-software-engineers-daily/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2F7-essential-websites-for-software-engineers-daily%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/a-complete-guide-to-the-product-design-process/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fa-complete-guide-to-the-product-design-process%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/ci-cd-for-llm-apps-run-tests-with-evidently-github-actions/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fci-cd-for-llm-apps-run-tests-with-evidently-github-actions%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/cloud-native-devsecops-resilient-software/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcloud-native-devsecops-resilient-software%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/free-llm-and-gen-ai-courses-to-take-in-2025/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffree-llm-and-gen-ai-courses-to-take-in-2025%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-not-write-garbage-code-by-linus-torvalds/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-not-write-garbage-code-by-linus-torvalds%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-choose-a-trusted-web-development-company-2025-guide/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-choose-a-trusted-web-development-company-2025-guide%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-tech-is-built-for-you-to-fail-why-smart-design-embraces-human-error/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-tech-is-built-for-you-to-fail-why-smart-design-embraces-human-error%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-optimize-your-seo-strategy-for-google-ai-overviews-in-2025/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-optimize-your-seo-strategy-for-google-ai-overviews-in-2025%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/is-wordpress-still-the-best-cms-in-2025/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fis-wordpress-still-the-best-cms-in-2025%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/our-startup-story-how-aexaware-infotech-was-born-in-anand-gujarat/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Four-startup-story-how-aexaware-infotech-was-born-in-anand-gujarat%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/owasp-top-10-llm-how-to-test-your-gen-ai-app-in-2025/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fowasp-top-10-llm-how-to-test-your-gen-ai-app-in-2025%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/react-19-2-features-that-transform-app-performance/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Freact-19-2-features-that-transform-app-performance%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/taming-data-variety-ai-ml-integration-cloud-devops/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftaming-data-variety-ai-ml-integration-cloud-devops%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/top-ai-tools-for-web-development-in-2025/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftop-ai-tools-for-web-development-in-2025%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/why-80-of-modern-systems-fail-not-from-bugs-but-from-over-engineering/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhy-80-of-modern-systems-fail-not-from-bugs-but-from-over-engineering%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/blog/why-stripes-api-never-breaks-date-based-versioning-explained/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhy-stripes-api-never-breaks-date-based-versioning-explained%2Findex.mdx&astroContentModuleFlag=true")]]);
		